ClinicaCesfam2023/Controllers/receta_medController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClinicaCesfam2023.Models;

namespace ClinicaCesfam2023.Controllers
{
    public class receta_medController : Controller
    {
        private CesfamClinicaEntities db = new CesfamClinicaEntities();

        // GET: receta_med
        public ActionResult Index()
        {
            var receta_med = db.receta_med.Include(r => r.paciente).Include(r => r.usuario);
            return View(receta_med.ToList());
        }

        // GET: receta_med/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            receta_med receta_med = db.receta_med.Find(id);
            if (receta_med == null)
            {
                return HttpNotFound();
            }
            return View(receta_med);
        }

        // GET: receta_med/Create
        public ActionResult Create()
        {
            ViewBag.paciente_rut_pac = new SelectList(db.paciente, "rut_pac", "nombre");
            ViewBag.usuario_rut_user = new SelectList(db.usuario, "rut_user", "tipo_usuario_tipo_user");
            return View();
        }

        // POST: receta_med/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_receta,descripcion,fecha_emi,paciente_rut_pac,usuario_rut_user")] receta_med receta_med)
        {
            if (ModelState.IsValid)
            {
                db.receta_med.Add(receta_med);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.paciente_rut_pac = new SelectList(db.paciente, "rut_pac", "nombre", receta_med.paciente_rut_pac);
            ViewBag.usuario_rut_user = new SelectList(db.usuario, "rut_user", "tipo_usuario_tipo_user", receta_med.usuario_rut_user);
            return View(receta_med);
        }

        // GET: receta_med/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            receta_med receta_med = db.receta_med.Find(id);
            if (receta_med == null)
            {
                return HttpNotFound();
            }
            ViewBag.paciente_rut_pac = new SelectList(db.paciente, "rut_pac", "nombre", receta_med.paciente_rut_pac);
            ViewBag.usuario_rut_user = new SelectList(db.usuario, "rut_user", "tipo_usuario_tipo_user", receta_med.usuario_rut_user);
            return View(receta_med);
        }

        // POST: receta_med/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_receta,descripcion,fecha_emi,paciente_rut_pac,usuario_rut_user")] receta_med receta_med)
        {
            if (ModelState.IsValid)
            {
                db.Entry(receta_med).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.paciente_rut_pac = new SelectList(db.paciente, "rut_pac", "nombre", receta_med.paciente_rut_pac);
            ViewBag.usuario_rut_user = new SelectList(db.usuario, "rut_user", "tipo_usuario_tipo_user", receta_med.usuario_rut_user);
            return View(receta_med);
        }

        // GET: receta_med/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            receta_med receta_med = db.receta_med.Find(id);
            if (receta_med == null)
            {
                return HttpNotFound();
            }
            return View(receta_med);
        }

        // POST: receta_med/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            receta_med receta_med = db.receta_med.Find(id);
            db.receta_med.Remove(receta_med);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClinicaCesfam2023/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @*Scripts.Render("~/bundles/modernizr")*@

</head>
<body class="sb-nav-fixed">
     
    

    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">Clínica Cesfam</a>



        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Settings</a></li>
                    <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="#!">Logout</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading"></div>
                        <a class="nav-link" href="/Home/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Inicio
                        </a>
                        <div class="sb-sidenav-menu-heading">Interfaz</div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Stock
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="/control_stock/Index">Control Stock</a>
                                <a class="nav-link" href="/medicamentoes/Index">Medicamentos</a>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Pacientes y Recetas
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                    Paciente
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="/pacientes/Index">Agregar Paciente</a>
                                        <a class="nav-link" href="/receta_med/Index">Recetas</a>
                                    </nav>
                                </div>
                                
                            </nav>
                        </div>
                        <div class="sb-sidenav-menu-heading">Comprar</div>
                        <a class="nav-link" href="/MedicamentoCompra/Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Comprar Medicamento
                        </a>
                        
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @RenderBody()



                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2023</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>



    @*RenderBody()*@

    @*<li>@Html.ActionLink("Inicio", "Index", "Home")</li>
        <li>@Html.ActionLink("Medicamentos", "Index", "medicamentoes")</li>
        <li>@Html.ActionLink("Receta", "Index", "receta_med")</li>*@


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/complementos")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>